<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datamodel" nsURI="http://at/sunplugged/cdv/datamodel" nsPrefix="at.sunplugged.cdv.datamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellResults" lowerBound="1"
        eType="#//CellResults" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellGroups" lowerBound="1"
        eType="#//CellGroups" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellDataSets" lowerBound="1"
        eType="#//CellDataSets" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationMethods" lowerBound="1"
        eType="#//EvaluationMethods" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellResults">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellResults" upperBound="-1"
        eType="#//CellResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="default..." iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationMethod" eType="#//EvaluationMethod"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataEvaluated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rawData" eType="#//CellMeasurementDataSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openCircuitVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortCircuitCurrent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelResistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesResistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPowerVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPowerCurrent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efficency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellGroup" upperBound="-1"
        eType="#//CellGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellMeasurmenetDataSet"
        eType="#//CellMeasurementDataSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellGroups">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellGroups" upperBound="-1"
        eType="#//CellGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellResults" upperBound="-1"
        eType="#//CellResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellDataSets">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellMesasurementDataSets"
        upperBound="-1" eType="#//CellMeasurementDataSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellMeasurementDataSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateMeasured" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voltageCurrentData" eType="#//VoltageCurrentData"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="area" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="powerInput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationMethods">
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationMethods" upperBound="-1"
        eType="#//EvaluationMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="VoltageCurrentData" instanceClassName="double[][]"/>
</ecore:EPackage>
